### PR TITLE
Added vehicle streamer

### PR DESCRIPTION
**Pull request by kurta999**
Include additions:

"This streamer have custom vehicle respawn system. The difference from samp; In SA-MP default vehicle system vehicle will be respawned when one player has been in vehicle before and respawn time passed since last player in vehicle exited - in streamer will be respawned when vehicle has been moved from spawn pos and respawn time passed. Nobody needs to be in vehicle. If somebody do not like this system, then I can create function which you can use to toggle new respawn system."

native Streamer_EnableDefaultVehicleRespawn(toggle); // on by default
#define STREAMER_TYPE_VEHICLE (7)

#define STREAMER_VEHICLE_TYPE_STATIC (0)
#define STREAMER_VEHICLE_TYPE_DYNAMIC (1)

enum
{
	E_STREAMER_ATTACHED_OBJECT,
	E_STREAMER_ATTACHED_PLAYER,
	E_STREAMER_ATTACHED_VEHICLE,
	E_STREAMER_ATTACH_OFFSET_X,
	E_STREAMER_ATTACH_OFFSET_Y,
	E_STREAMER_ATTACH_OFFSET_Z,
	E_STREAMER_ATTACH_R_X,
	E_STREAMER_ATTACH_R_Y,
	E_STREAMER_ATTACH_R_Z,
	E_STREAMER_ATTACH_X,
	E_STREAMER_ATTACH_Y,
	E_STREAMER_ATTACH_Z,
	E_STREAMER_COLOR,
	E_STREAMER_COLOR_2,
	E_STREAMER_DRAW_DISTANCE,
	E_STREAMER_EXTRA_ID,
	E_STREAMER_HEALTH,
	E_STREAMER_INTERIOR_ID,
	E_STREAMER_MAX_X,
	E_STREAMER_MAX_Y,
	E_STREAMER_MAX_Z,
	E_STREAMER_MIN_X,
	E_STREAMER_MIN_Y,
	E_STREAMER_MIN_Z,
	E_STREAMER_MODEL_ID,
	E_STREAMER_MOVE_R_X,
	E_STREAMER_MOVE_R_Y,
	E_STREAMER_MOVE_R_Z,
	E_STREAMER_MOVE_SPEED,
	E_STREAMER_MOVE_X,
	E_STREAMER_MOVE_Y,
	E_STREAMER_MOVE_Z,
	E_STREAMER_NEXT_X,
	E_STREAMER_NEXT_Y,
	E_STREAMER_NEXT_Z,
	E_STREAMER_PAINTJOB,
	E_STREAMER_PLAYER_ID,
	E_STREAMER_QUAT_W,
	E_STREAMER_QUAT_X,
	E_STREAMER_QUAT_Y,
	E_STREAMER_QUAT_Z,
	E_STREAMER_RESPAWN_TIME,
	E_STREAMER_R_X,
	E_STREAMER_R_Y,
	E_STREAMER_R_Z,
	E_STREAMER_SIZE,
	E_STREAMER_SPAWN_ANGLE,
	E_STREAMER_SPAWN_COLOR_1,
	E_STREAMER_SPAWN_COLOR_2,
	E_STREAMER_SPAWN_X,
	E_STREAMER_SPAWN_Y,
	E_STREAMER_SPAWN_Z,
	E_STREAMER_SIREN,
	E_STREAMER_STREAM_DISTANCE,
	E_STREAMER_STYLE,
	E_STREAMER_SYNC_ROTATION,
	E_STREAMER_TEST_LOS,
	E_STREAMER_TYPE,
	E_STREAMER_WORLD_ID,
	E_STREAMER_X,
	E_STREAMER_Y,
	E_STREAMER_Z
}

native Streamer_EnableDefaultVehicleRespawn(toggle); // on by default

native AttachDynamicObjectToVehicle(objectid, vehicleid, Float:offsetx, Float:offsety, Float:offsetz, Float:rx, Float:ry, Float:rz, vehicletype = STREAMER_VEHICLE_TYPE_DYNAMIC);
native Text3D:CreateDynamic3DTextLabel(const text[], color, Float:x, Float:y, Float:z, Float:drawdistance, attachedplayer = INVALID_PLAYER_ID, attachedvehicle = INVALID_VEHICLE_ID, vehicletype = STREAMER_VEHICLE_TYPE_DYNAMIC, testlos = 0, worldid = -1, interiorid = -1, playerid = -1, Float:streamdistance = 100.0);
native AttachDynamicAreaToVehicle(areaid, vehicleid, vehicletype = STREAMER_VEHICLE_TYPE_DYNAMIC);

// Natives (Vehicles)

native CreateDynamicVehicle(modelid, Float:fX, Float:fY, Float:fZ, Float:fRot, color1, color2, respawndelay, addsiren = 0, worldid = 0, interiorid = 0, Float:streamdistance = 300.0);
native DestroyDynamicVehicle(vehicleid);
native IsValidDynamicVehicle(vehicleid);
native IsDynamicVehicleStreamedIn(vehicleid, forplayerid);
native GetDynamicVehicleSpawnInfo(vehicleid, &Float:fX, &Float:fY, &Float:fZ, &Float:fRot, &color1, &color2, &siren);
native GetDynamicVehiclePos(vehicleid, &Float:x, &Float:y, &Float:z);
native SetDynamicVehiclePos(vehicleid, Float:x, Float:y, Float:z);
native GetDynamicVehicleZAngle(vehicleid, &Float:z_angle);
native GetDynamicVehicleRotationQuat(vehicleid, &Float:w, &Float:x, &Float:y, &Float:z);
native SetDynamicVehicleZAngle(vehicleid, Float:z_angle);
native Float:GetDynamicVehDistanceFromPoint(vehicleid, Float:X, Float:Y, Float:Z);
native SetDynamicVehParamsForPlayer(vehicleid,playerid,objective,doorslocked);
native SetDynamicVehicleParamsEx(vehicleid, engine, lights, alarm, doors, bonnet, boot, objective);
native GetDynamicVehicleParamsEx(vehicleid, &engine, &lights, &alarm, &doors, &bonnet, &boot, &objective);
native GetDynamicVehParamsSirenState(vehicleid);
native SetDynamicVehParamsCarDoors(vehicleid, driver, passenger, backleft, backright);
native GetDynamicVehParamsCarDoors(vehicleid, &driver, &passenger, &backleft, &backright);
native SetDynamicVehParamsCarWindows(vehicleid, driver, passenger, backleft, backright);
native GetDynamicVehParamsCarWindows(vehicleid, &driver, &passenger, &backleft, &backright);
native SetDynamicVehicleToRespawn(vehicleid);
native LinkDynamicVehicleToInterior(vehicleid, interiorid);
native GetDynamicVehicleInterior(vehicleid);
native AddDynamicVehicleComponent(vehicleid, componentid);
native RemoveDynamicVehicleComponent(vehicleid, componentid);
native ChangeDynamicVehicleColor(vehicleid, color1, color2);
native GetDynamicVehicleColor(vehicleid, &color1, &color2);
native ChangeDynamicVehiclePaintjob(vehicleid, paintjobid);
native GetDynamicVehiclePaintjob(vehicleid);
native SetDynamicVehicleHealth(vehicleid, Float:health);
native GetDynamicVehicleHealth(vehicleid, &Float:health);
native AttachTrailerToDynamicVehicle(trailerid, vehicleid);
native DetachTrailerFromDynamicVeh(vehicleid);
native IsTrailerAttachedToDynamicVeh(vehicleid);
native GetDynamicVehicleTrailer(vehicleid);
native SetDynamicVehicleNumberPlate(vehicleid, plate[]);
native GetDynamicVehicleNumberPlate(vehicleid, plate[], size = sizeof(plate));
native GetDynamicVehicleModel(vehicleid);
native GetDynamicVehComponentInSlot(vehicleid, slot); // There is 1 slot for each CARMODTYPE_*
native RepairDynamicVehicle(vehicleid); // Repairs the damage model and resets the health
native GetDynamicVehicleVelocity(vehicleid, &Float:X, &Float:Y, &Float:Z);
native SetDynamicVehicleVelocity(vehicleid, Float:X, Float:Y, Float:Z);
native SetDynamicVehAngularVelocity(vehicleid, Float:X, Float:Y, Float:Z);
native GetDynamicVehicleDamageStatus(vehicleid, &panels, &doors, &lights, &tires);
native UpdateDynamicVehDamageStatus(vehicleid, panels, doors, lights, tires);
native SetDynamicVehicleVirtualWorld(vehicleid, worldid);
native GetDynamicVehicleVirtualWorld(vehicleid);
native GetPlayerSurfingDynamicVehID(playerid);
native PutPlayerInDynamicVehicle(playerid, vehicleid, seatid);
native GetPlayerDynamicVehicleID(playerid);
native IsPlayerInDynamicVehicle(playerid, vehicleid);
native IsPlayerInAnyDynamicVehicle(vehicleid);
native IsDynamicVehicleOccupied(vehicleid);
native PlayerSpectateDynamicVehicle(playerid, targetvehicleid, mode = 0);

### CODE REVIEW

**Comment by Crayder** [comment]
I'd like to see this as an optional module in the master branch. Like, it would be off by default but can be enabled in OnGameModeInit.

**Comment by kurta999** [comment]
There is a vehicle-streamer branch by currently, so that means Incognito won't include it into official release. Anyway, if it would be in official branch, and you won't want to use vehicle streamer then you just need to use default vehicle functions, like before and this won't affect you at all.

**Comment by kurta999** [comment]
For a second try it looks like that i have finally done with vehicle streamer. Now it works without vehicle disappearing, everything works well. I would like to create pull request, but before Incognito you could check my ocommit and say what you dont like. I will repair those before pr, in this way its easyer to both of us.

https://github.com/kurta999/samp-streamer-plugin/commit/7aa1584de8601b33f040566f4b9561a1314fc0a8

**Comment by rt-2** [comment]
I'm skeptical, but this is a good step forward, thank you @kurta999

**Pull request merged**
