### PR TITLE
Fix #316 for actors

### LINKED ISSUE #316: Something wrong with pickups in more than one virtual world
Look at the video: https://youtu.be/TJ51a1erZig

Code:
```Pawn
#include <a_samp>
#include "zcmd"
#include "streamer"

public OnGameModeInit()
{
	CreateDynamicPickupEx(1275, 38, 0.0, 0.0, 4.0, .worlds = {0, 1});
	return 1;
}

CMD:world(playerid, params[])
{
	SetPlayerVirtualWorld(playerid, strval(params));
	return 1;
}

CMD:info(playerid, params[])
{
	new string[144];
	format(string, sizeof(string), "virtualworld: %d", GetPlayerVirtualWorld(playerid));
	SendClientMessage(playerid, -1, string);
	return 1;
}
```
It can be fixed like this:
```Pawn
CMD:world(playerid, params[])
{
	SetPlayerVirtualWorld(playerid, strval(params));
	Streamer_ToggleItem(playerid, STREAMER_TYPE_PICKUP, test_pickup_id, false);
	SetTimerEx("test", 500, 0, "d", playerid);
	return 1;
}
forward test(playerid);
public test(playerid)
{
	Streamer_ToggleItem(playerid, STREAMER_TYPE_PICKUP, test_pickup_id, true);
}
```
Tested on `1.8.2`, `1.9.4`

### PR DESCRIPTION
**Pull request by ziggi**

### CODE REVIEW

**Comment by karimcambridge** [comment]
Can you describe the fix and how it fixes the described problem in #316

**Comment by ziggi** [comment]
No.

**Comment by karimcambridge** [comment]
lmfao

**Comment by ziggi** [comment]
This PR remakes internal actor key from the `actorId` to the `actorId, worldId` pair, so, it requires to add additional loop wherever actors are used.

**Pull request merged**
