### PR TITLE
Added function Streamer_GetNearbyItems

### LINKED ISSUE #128: Exposing internal indexes to Pawn for faster looping
A quick feature proposal for something I expect will be quite easy to implement:

I often find myself wanting to find the closest X objects to point Y (not necessarily a player) which, without spacial indexing, involves looping every object in Pawn. The problem is, SS can have up to 20,000 [SIF items](https://github.com/Southclaw/SIF/blob/master/SIF/Item.pwn#L145) (SIF item = object + area, not a "streamer item") in the game-world at once.

I'd love to expose the indexing method that the streamer uses in some way so I can, for example, get a list of "streamer items" (objects, etc) for a specific grid or the closest X items to a point in the world. I planned on attempting this myself but I don't know the streamer's internals very well so I thought I'd open an issue for it first to get some feedback on the idea.

Getting the closest X items to a player is [easy](https://github.com/Southclaw/SIF/blob/master/SIF/Button.pwn#L915-L925) because the player walking near the item is recorded via a streamer area, however this isn't so easy for arbitrary points (other items, etc) which I use for explosive items triggering nearby items to explode/break.

### PR DESCRIPTION
**Pull request by Southclaw**
Writes to an array the nearest n items to position (x, y) where "nearest" is items in the surrounding cells to position (x, y), returns n.

Resolves #128

### CODE REVIEW

**Comment by Crayder** [comment]
No search flags... D:

Just kidding, this is a great addition. I still think you should also add an area range one too with min-x, min-y, max-x, max-y, and optional z.

Flags are definitely something I want but can be done later. Maybe I can even finally get a feel for the internals of streamer myself and do it. Since it's a separate suggestion (but would be used in both of your functions and perhaps more) O may open a separate issue.

**Comment by Southclaw** [comment]
I was thinking of that, after I replied to Patrik regarding the uselessness of sorting the items in descending order I realised that a range would be useful for that.

It would also help with the arbitrariness of sorted items, for example an item could be closer to the point in two dimensions (x, y) but hundreds of metres in the air (in an interior perhaps) and it would still be regarded closer than an item that may be slightly further away in the (x, y) plane but actually closer in (x, y, z) space. I'll resolve this by adding a `z` parameter and making the distance calculations 3D rather than 2D. Or I could give the function a `dimensions` parameter similar to Streamer_GetDistanceToItem.

**Comment by IstuntmanI** [comment]
Also, virtual world and interior parameters would be useful.

**Comment by Southclaw** [comment]
Ah yes of course, I completely forgot about those (probably because I never use them!)

**Comment by Crayder** [comment]
So... my search flag suggestion could benefit you too...

You could set the 'explosion' flag on objects that should explode... :D

**Comment by Southclaw** [comment]
Yeah, I'll have a go at implementing flags once this is done. I would imagine it's similar to the world/interior collections but creating the collections dynamically somehow. I'm sure boost has a utility for that!

**Comment by samp-incognito** [comment]
This looks good, thanks!

A couple of things:
- Make sure you use an `std::multimap` iterator in those loops (e.g., https://github.com/Southclaw/samp-streamer-plugin/blob/a6d9f2f7a7e15108b321029eda80e961354b6e4d/src/natives/miscellaneous.cpp#L1356).
- You can square the range and use `boost::geometry::comparable_distance` instead. This will be faster than the other function which calculates the square root internally.

**Comment by Southclaw** [comment]
Thanks for the feedback! I'll update the PR tomorrow. I'm currently using this function [here](https://github.com/Southclaw/ScavengeSurvive/blob/develop/gamemodes/sss/core/world/defences.pwn#L1185-L1219) now so that should serve as a form of test as I'm actively developing quite a few features that will use this new function.

**Pull request merged**
