### PR TITLE
Adds GetDynamicAreaType

### PR DESCRIPTION
**Pull request by IstuntmanI**
Solves #255.

### CODE REVIEW

**Comment by Romz24** [comment]
why STREAMER_MAX_AREA_TYPES is value 5, instead of 6?
I counted 6 types based on what you wrote.

**Comment by IstuntmanI** [comment]
The value was 5, it should be 6 because of this:
```cpp
#define STREAMER_AREA_TYPE_CIRCLE (0)
#define STREAMER_AREA_TYPE_CYLINDER (1)
#define STREAMER_AREA_TYPE_SPHERE (2)
#define STREAMER_AREA_TYPE_RECTANGLE (3)
#define STREAMER_AREA_TYPE_CUBOID (4)
#define STREAMER_AREA_TYPE_POLYGON (5)
```
It starts from 0 and ends at 5 => there are 6 area types. Incognito said that he probably forgot to increase that definition's value when he added a new area type.

**Comment by Southclaws** [comment]
For those kinds of tasks, I like using an untagged enumerator for simple incrementing constants and finishing it off with a MAX symbol:

```pawn
enum {
	STREAMER_AREA_TYPE_CIRCLE
	STREAMER_AREA_TYPE_CYLINDER
	STREAMER_AREA_TYPE_SPHERE
	STREAMER_AREA_TYPE_RECTANGLE
	STREAMER_AREA_TYPE_CUBOID
	STREAMER_AREA_TYPE_POLYGON

	STREAMER_MAX_AREA_TYPES
}
```

Then you don't need to worry too much about remembering to update the values/max.

**Comment by IstuntmanI** [comment]
Yeah, that's what I would use too.

I tested this function and it works fine.

**Pull request merged**
