### PR TITLE
Fixes for actors

### PR DESCRIPTION
**Pull request by ziggi**
- Fix GetPlayerTargetDynamicActor
- Fix setFloatData Health and Rotation actor params

### CODE REVIEW

**Comment by IstuntmanI** [comment]
Also, it looks like SetActorFacingAngle requires restreaming for players, or it will stay at the same angle until restreamed. You should recreate the actor when the angle is changed.

**Comment by ziggi** [comment]
You are right, thanks, fixed.

**Comment by IstuntmanI** [comment]
Another thing: virtual world 0 streams the actor in virtual world 0 only (sometimes it looks like it appears and disappears fast, not sure), as it should, and -1 streams the actor in all worlds without problems, as it should. But there seems to be a problem when the world has a different value, it isn't streaming at all. I see that pickups have problems for multiple worlds too.

CreatePickup has "vworld" parameter in it, a value of -1 shows it in all world, but for actors you have to use SetActorVirtualWorld (AFAIK, -1 won't show it in all worlds).

My suggestion would be to remove the multi worlds handling from actors. So **boost::unordered_set<int> worlds;** from item.h from **struct Actor** would be only a **int worlds;** .  Also, removing to ability to use array data functions for world IDs for actors. I guess that this is the best solution.

**Comment by IstuntmanI** [comment]
You need to reapply the animation too when you recreate the actor:
```c++
if (i->second->anim)
{
	sampgdk::ApplyActorAnimation(internalID, i->second->anim->lib.c_str(), i->second->anim->name.c_str(), i->second->anim->delta, i->second->anim->loop, i->second->anim->lockx, i->second->anim->locky, i->second->anim->freeze, i->second->anim->time);
}
```

Also, in streamer.cpp I see this piece of code:
```c++
core->getData()->internalActors.insert(std::make_pair(i->second->actorID, internalID));
```
I don't know if this is correct, but shouldn't the internalID from internalActors be updated somehow when the actor is recreated, as it may have another internal ID ?

**Comment by IstuntmanI** [comment]
Thanks for your work, ziggi.

@samp-incognito You should pull this and my pull request. Also, look at the thing I said about virtual worlds (pickups aren't behaving well when they have multiple virtual worlds too). If you think that we should change the world ID to only an int for actors and pickups I'll try to create another pull request for this, at least for actors.

This shows the pickup only in virtual world 1:
```pawn
new PICKUPP = CreateDynamicPickup( 1000, 1, 0.0, 0.0, 4.0, .streamdistance = 100.0, .worldid = 3 );
Streamer_AppendArrayData( STREAMER_TYPE_PICKUP, PICKUPP, E_STREAMER_WORLD_ID, 1 );
Streamer_AppendArrayData( STREAMER_TYPE_PICKUP, PICKUPP, E_STREAMER_WORLD_ID, 2 );
```

**Comment by samp-incognito** [comment]
It should just create the pickup in the player's current virtual world in that case (https://github.com/samp-incognito/samp-streamer-plugin/blob/master/src/streamer.cpp#L852). If you had been in virtual world 2, for example, it would have created the pickup there instead of virtual world 1. It's not ideal, of course, but nothing about pickups really is since you can't create them per player.

I suppose for actors, you'd need to do this too, and use SetActorVirtualWorld after the actor has been created.

**Comment by IstuntmanI** [comment]
My bad, you are right. I tested it again and that is exactly what it does. Well, it would be fine for the actors to have the same behaviour.

**Comment by ziggi** [comment]
Fixed.

**Comment by IstuntmanI** [comment]
Nope. "world" doesn't exists in Actor struct. You have to:
- Add "int worldID;" to Item.h at the Actor struct, after "float health;" and change "world" from your last commit to "worldID" (so it would match Pickup's "worldID").
- In streamer.cpp after
```c++
boost::unordered_map<int, int>::iterator i = core->getData()->internalActors.find(p->first);
```
you need to add
```c++
if (i == core->getData()->internalActors.end())
{
	p->second->worldID = !p->second->worlds.empty() ? player.worldID : -1;
}
```

That's all, I guess.

**Comment by ziggi** [comment]
Ohh, thanks:)

**Comment by samp-incognito** [comment]
Looks good now, thanks.

**Pull request merged**
